# Generated by Django 5.0.2 on 2024-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_task'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Category',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
