# Generated by Django 5.0.2 on 2024-02-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Category',
            new_name='category',
        ),
    ]
